Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             GET, HEAD, OPTIONS             /static/[filename]
custom_webhook.health                              GET, HEAD, OPTIONS             /webhooks/rest/
custom_webhook.receive                             POST, OPTIONS                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hi' with intent '{'confidence': 0.9553435444831848, 'name': 'greet'}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 

Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "buttons": null,
  "elements": null,
  "attachment": null
})'
Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'was gibt es diese woche zu essen' with intent '{'confidence': 0.9736260175704956, 'name': 'ask'}' and entities '[{'extractor': 'ner_crf', 'confidence': 0.8627070097632291, 'start': 18, 'entity': 'time', 'value': 'woche', 'end': 23}]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 

Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.97.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'was gibt es heute zu essen' with intent '{'confidence': 0.9721738696098328, 'name': 'ask'}' and entities '[{'extractor': 'ner_crf', 'confidence': 0.977958308053911, 'start': 12, 'entity': 'time', 'value': 'heute', 'end': 17}]'
Logged UserUtterance - tracker now has 8 events
Current slot values: 

Current tracker state [{'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}, {'intent_ask': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.93.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '' with intent '{'confidence': 0.0, 'name': None}' and entities '[]'
Logged UserUtterance - tracker now has 10 events
Current slot values: 

Current tracker state [{'intent_ask': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}, {'intent_ask': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}, {'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 0.78.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "buttons": null,
  "elements": null,
  "attachment": null
})'
Current tracker state [{'intent_ask': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}, {'prev_action_listen': 1.0}, {'prev_utter_ask_howcanhelp': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.91.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '' with intent '{'confidence': 0.0, 'name': None}' and entities '[]'
Logged UserUtterance - tracker now has 14 events
Current slot values: 

Current tracker state [{'prev_action_listen': 1.0}, {'prev_utter_ask_howcanhelp': 1.0}, {'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.83.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'was gibt es heute zu essen' with intent '{'confidence': 0.9721738696098328, 'name': 'ask'}' and entities '[{'extractor': 'ner_crf', 'confidence': 0.977958308053911, 'start': 12, 'entity': 'time', 'value': 'heute', 'end': 17}]'
Logged UserUtterance - tracker now has 16 events
Current slot values: 

Current tracker state [{'prev_utter_ask_howcanhelp': 1.0}, {'prev_action_listen': 1.0}, {'intent_ask': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.86.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'hi' with intent '{'confidence': 0.9553435444831848, 'name': 'greet'}' and entities '[]'
Logged UserUtterance - tracker now has 18 events
Current slot values: 

Current tracker state [{'prev_action_listen': 1.0}, {'intent_ask': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 0.74.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "buttons": null,
  "elements": null,
  "attachment": null
})'
Current tracker state [{'intent_ask': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.96.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'was gibt es diese woche zu essen' with intent '{'confidence': 0.9736260175704956, 'name': 'ask'}' and entities '[{'extractor': 'ner_crf', 'confidence': 0.8627070097632291, 'start': 18, 'entity': 'time', 'value': 'woche', 'end': 23}]'
Logged UserUtterance - tracker now has 22 events
Current slot values: 

Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.97.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '\stop' with intent '{'confidence': 0.0, 'name': None}' and entities '[]'
Logged UserUtterance - tracker now has 24 events
Current slot values: 

Current tracker state [{'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}, {'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.90.
Action 'action_listen' ended with events '[]'
Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             GET, HEAD, OPTIONS             /static/[filename]
custom_webhook.health                              GET, HEAD, OPTIONS             /webhooks/rest/
custom_webhook.receive                             OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hi' with intent '{'confidence': 0.9553435444831848, 'name': 'greet'}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 

Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "elements": null,
  "attachment": null,
  "buttons": null
})'
Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '' with intent '{'confidence': 0.0, 'name': None}' and entities '[]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 

Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.96.
Action 'action_listen' ended with events '[]'
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             GET, OPTIONS, HEAD             /static/[filename]
custom_webhook.health                              GET, OPTIONS, HEAD             /webhooks/rest/
custom_webhook.receive                             OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message '/greet' with intent '{'name': 'greet', 'confidence': 1.0}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 

Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "attachment": null,
  "elements": null,
  "buttons": null
})'
Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/ask_week' with intent '{'name': 'ask_week', 'confidence': 1.0}' and entities '[]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 

Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'intent_ask_week': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Feature 'intent_ask_week' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.96.
Action 'action_listen' ended with events '[]'
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             HEAD, OPTIONS, GET             /static/[filename]
custom_webhook.health                              HEAD, OPTIONS, GET             /webhooks/rest/
custom_webhook.receive                             OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message '/greet' with intent '{'confidence': 1.0, 'name': 'greet'}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 

Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "buttons": null,
  "attachment": null,
  "elements": null
})'
Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/ask_week' with intent '{'confidence': 1.0, 'name': 'ask_week'}' and entities '[]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 

Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_ask_week': 1.0}]
There is no memorised next action
Feature 'intent_ask_week' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.96.
Action 'action_listen' ended with events '[]'
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             GET, HEAD, OPTIONS             /static/[filename]
custom_webhook.health                              GET, HEAD, OPTIONS             /webhooks/rest/
custom_webhook.receive                             POST, OPTIONS                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message '/greet' with intent '{'confidence': 1.0, 'name': 'greet'}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 

Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "buttons": null,
  "attachment": null,
  "elements": null
})'
Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/ask_week' with intent '{'confidence': 1.0, 'name': 'ask_week'}' and entities '[]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 

Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask_week': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '4'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_cannot_do_that_yet' with prob 1.00.
Action 'utter_cannot_do_that_yet' ended with events '[]'
Bot utterance 'BotUttered(text: Das wurde mir noch nicht beigebracht., data: {
  "buttons": null,
  "attachment": null,
  "elements": null
})'
Current tracker state [{'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask_week': 1.0, 'prev_action_listen': 1.0}, {'intent_ask_week': 1.0, 'prev_utter_cannot_do_that_yet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/greet' with intent '{'confidence': 1.0, 'name': 'greet'}' and entities '[]'
Logged UserUtterance - tracker now has 10 events
Current slot values: 

Current tracker state [{'intent_ask_week': 1.0, 'prev_action_listen': 1.0}, {'intent_ask_week': 1.0, 'prev_utter_cannot_do_that_yet': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "buttons": null,
  "attachment": null,
  "elements": null
})'
Current tracker state [{'intent_ask_week': 1.0, 'prev_utter_cannot_do_that_yet': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/ask_today' with intent '{'confidence': 1.0, 'name': 'ask_today'}' and entities '[]'
Logged UserUtterance - tracker now has 14 events
Current slot values: 

Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask_today': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '5'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_inform_today' with prob 1.00.
Encountered an exception while running action 'action_inform_today'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
The model predicted the custom action 'action_inform_today' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/actions/action.py", line 306, in run
    "".format(self.name(), DOCS_BASE_URL))
Exception: The model predicted the custom action 'action_inform_today' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Action 'action_inform_today' ended with events '[]'
Current tracker state [{'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask_today': 1.0, 'prev_action_listen': 1.0}, {'prev_action_inform_today': 1.0, 'intent_ask_today': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             GET, OPTIONS, HEAD             /static/[filename]
custom_webhook.health                              GET, OPTIONS, HEAD             /webhooks/rest/
custom_webhook.receive                             OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message '/g/greet' with intent '{'name': 'g/greet', 'confidence': 1.0}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 

Current tracker state [None, {}, {'intent_g/greet': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Feature 'intent_g/greet' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_2_KerasPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 0.63.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{}, {'intent_g/greet': 1.0, 'prev_action_listen': 1.0}, {'intent_g/greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}]
There is no memorised next action
Feature 'intent_g/greet' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Feature 'intent_g/greet' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.81.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/ask_today' with intent '{'name': 'ask_today', 'confidence': 1.0}' and entities '[]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 

Current tracker state [{'intent_g/greet': 1.0, 'prev_action_listen': 1.0}, {'intent_g/greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'intent_ask_today': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Feature 'intent_g/greet' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Feature 'intent_g/greet' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.80.
Action 'action_listen' ended with events '[]'
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             GET, HEAD, OPTIONS             /static/[filename]
custom_webhook.health                              GET, HEAD, OPTIONS             /webhooks/rest/
custom_webhook.receive                             POST, OPTIONS                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message '/greet' with intent '{'name': 'greet', 'confidence': 1.0}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 

Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "attachment": null,
  "buttons": null,
  "elements": null
})'
Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/ask_today' with intent '{'name': 'ask_today', 'confidence': 1.0}' and entities '[]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 

Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask_today': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '5'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_inform_today' with prob 1.00.
Encountered an exception while running action 'action_inform_today'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
The model predicted the custom action 'action_inform_today' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/actions/action.py", line 306, in run
    "".format(self.name(), DOCS_BASE_URL))
Exception: The model predicted the custom action 'action_inform_today' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Action 'action_inform_today' ended with events '[]'
Current tracker state [{'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask_today': 1.0, 'prev_action_listen': 1.0}, {'intent_ask_today': 1.0, 'prev_action_inform_today': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             GET, HEAD, OPTIONS             /static/[filename]
custom_webhook.health                              GET, HEAD, OPTIONS             /webhooks/rest/
custom_webhook.receive                             OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message '/greet' with intent '{'name': 'greet', 'confidence': 1.0}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 

Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "buttons": null,
  "attachment": null,
  "elements": null
})'
Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/ask_today' with intent '{'name': 'ask_today', 'confidence': 1.0}' and entities '[]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 

Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'prev_action_listen': 1.0, 'intent_ask_today': 1.0}]
There is a memorised next action '5'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_inform_today' with prob 1.00.
Encountered an exception while running action 'action_inform_today'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
The model predicted the custom action 'action_inform_today' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/actions/action.py", line 306, in run
    "".format(self.name(), DOCS_BASE_URL))
Exception: The model predicted the custom action 'action_inform_today' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Action 'action_inform_today' ended with events '[]'
Current tracker state [{'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'prev_action_listen': 1.0, 'intent_ask_today': 1.0}, {'prev_action_inform_today': 1.0, 'intent_ask_today': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_inform_today'. Couldn't connect to the server at 'http://localhost:5055/webhook'. Is the server running? Error: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86a63c5a58>: Failed to establish a new connection: [Errno 111] Connection refused',))
Encountered an exception while running action 'action_inform_today'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 171, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 79, in create_connection
    raise err
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/connection.py", line 69, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 354, in _make_request
    conn.request(method, url, **httplib_request_kw)
  File "/usr/lib/python3.5/http/client.py", line 1106, in request
    self._send_request(method, url, body, headers)
  File "/usr/lib/python3.5/http/client.py", line 1151, in _send_request
    self.endheaders(body)
  File "/usr/lib/python3.5/http/client.py", line 1102, in endheaders
    self._send_output(message_body)
  File "/usr/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/usr/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 196, in connect
    conn = self._new_conn()
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connection.py", line 180, in _new_conn
    self, "Failed to establish a new connection: %s" % e)
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPConnection object at 0x7f86a63c5a58>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 398, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86a63c5a58>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/actions/action.py", line 312, in run
    json=json, method="post", timeout=DEFAULT_REQUEST_TIMEOUT)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/utils.py", line 641, in request
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 513, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPConnectionPool(host='localhost', port=5055): Max retries exceeded with url: /webhook (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f86a63c5a58>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/actions/action.py", line 324, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Failed to run custom action 'action_inform_today'. Couldn't connect to the server at 'http://localhost:5005/webhook'. Is the server running? Error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Encountered an exception while running action 'action_inform_today'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/actions/action.py", line 312, in run
    json=json, method="post", timeout=DEFAULT_REQUEST_TIMEOUT)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/utils.py", line 641, in request
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/actions/action.py", line 324, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             HEAD, GET, OPTIONS             /static/[filename]
custom_webhook.health                              HEAD, GET, OPTIONS             /webhooks/rest/
custom_webhook.receive                             POST, OPTIONS                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message '/greet' with intent '{'confidence': 1.0, 'name': 'greet'}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 

Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "elements": null,
  "attachment": null,
  "buttons": null
})'
Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/adk_today' with intent '{'confidence': 1.0, 'name': 'adk_today'}' and entities '[]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 

Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_adk_today': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Feature 'intent_adk_today' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.91.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/ask_today' with intent '{'confidence': 1.0, 'name': 'ask_today'}' and entities '[]'
Logged UserUtterance - tracker now has 8 events
Current slot values: 

Current tracker state [{'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_adk_today': 1.0, 'prev_action_listen': 1.0}, {'intent_ask_today': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Feature 'intent_adk_today' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.87.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/greet' with intent '{'confidence': 1.0, 'name': 'greet'}' and entities '[]'
Logged UserUtterance - tracker now has 10 events
Current slot values: 

Current tracker state [{'intent_adk_today': 1.0, 'prev_action_listen': 1.0}, {'intent_ask_today': 1.0, 'prev_action_listen': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is no memorised next action
Feature 'intent_adk_today' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_2_KerasPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 0.75.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "elements": null,
  "attachment": null,
  "buttons": null
})'
Current tracker state [{'intent_ask_today': 1.0, 'prev_action_listen': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.89.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/ask_week' with intent '{'confidence': 1.0, 'name': 'ask_week'}' and entities '[]'
Logged UserUtterance - tracker now has 14 events
Current slot values: 

Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask_week': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '4'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_cannot_do_that_yet' with prob 1.00.
Action 'utter_cannot_do_that_yet' ended with events '[]'
Bot utterance 'BotUttered(text: Das wurde mir noch nicht beigebracht., data: {
  "elements": null,
  "attachment": null,
  "buttons": null
})'
Current tracker state [{'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask_week': 1.0, 'prev_action_listen': 1.0}, {'intent_ask_week': 1.0, 'prev_utter_cannot_do_that_yet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/greet' with intent '{'confidence': 1.0, 'name': 'greet'}' and entities '[]'
Logged UserUtterance - tracker now has 18 events
Current slot values: 

Current tracker state [{'intent_ask_week': 1.0, 'prev_action_listen': 1.0}, {'intent_ask_week': 1.0, 'prev_utter_cannot_do_that_yet': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "elements": null,
  "attachment": null,
  "buttons": null
})'
Current tracker state [{'intent_ask_week': 1.0, 'prev_utter_cannot_do_that_yet': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/ask_today' with intent '{'confidence': 1.0, 'name': 'ask_today'}' and entities '[]'
Logged UserUtterance - tracker now has 22 events
Current slot values: 

Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask_today': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '5'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_inform_today' with prob 1.00.
Calling action endpoint to run action 'action_inform_today'.
Failed to run custom action 'action_inform_today'. Couldn't connect to the server at 'http://localhost:5005/webhook'. Is the server running? Error: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))
Encountered an exception while running action 'action_inform_today'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
Failed to execute custom action.
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 104] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 445, in send
    timeout=timeout
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/local/lib/python3.5/dist-packages/urllib3/util/retry.py", line 367, in increment
    raise six.reraise(type(error), error, _stacktrace)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/packages/six.py", line 685, in reraise
    raise value.with_traceback(tb)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 384, in _make_request
    six.raise_from(e, None)
  File "<string>", line 2, in raise_from
  File "/usr/local/lib/python3.5/dist-packages/urllib3/connectionpool.py", line 380, in _make_request
    httplib_response = conn.getresponse()
  File "/usr/lib/python3.5/http/client.py", line 1197, in getresponse
    response.begin()
  File "/usr/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/usr/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/usr/lib/python3.5/socket.py", line 575, in readinto
    return self._sock.recv_into(b)
urllib3.exceptions.ProtocolError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/actions/action.py", line 312, in run
    json=json, method="post", timeout=DEFAULT_REQUEST_TIMEOUT)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/utils.py", line 641, in request
    **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/api.py", line 58, in request
    return session.request(method=method, url=url, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 512, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/sessions.py", line 622, in send
    r = adapter.send(request, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/requests/adapters.py", line 495, in send
    raise ConnectionError(err, request=request)
requests.exceptions.ConnectionError: ('Connection aborted.', ConnectionResetError(104, 'Connection reset by peer'))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/actions/action.py", line 324, in run
    raise Exception("Failed to execute custom action.")
Exception: Failed to execute custom action.
Action 'action_inform_today' ended with events '[]'
Current tracker state [{'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask_today': 1.0, 'prev_action_listen': 1.0}, {'intent_ask_today': 1.0, 'prev_action_inform_today': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Encountered an exception while running action 'action_inform_today'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
The model predicted the custom action 'action_inform_today' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/actions/action.py", line 306, in run
    "".format(self.name(), DOCS_BASE_URL))
Exception: The model predicted the custom action 'action_inform_today' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Encountered an exception while running action 'action_inform_today'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
The model predicted the custom action 'action_inform_today' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/actions/action.py", line 306, in run
    "".format(self.name(), DOCS_BASE_URL))
Exception: The model predicted the custom action 'action_inform_today' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Encountered an exception while running action 'action_inform_today'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
The model predicted the custom action 'action_inform_today' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/actions/action.py", line 306, in run
    "".format(self.name(), DOCS_BASE_URL))
Exception: The model predicted the custom action 'action_inform_today' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             HEAD, GET, OPTIONS             /static/[filename]
custom_webhook.health                              HEAD, GET, OPTIONS             /webhooks/rest/
custom_webhook.receive                             OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message '/greet' with intent '{'name': 'greet', 'confidence': 1.0}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 

Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "buttons": null,
  "attachment": null,
  "elements": null
})'
Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/ask_today' with intent '{'name': 'ask_today', 'confidence': 1.0}' and entities '[]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 

Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'prev_action_listen': 1.0, 'intent_ask_today': 1.0}]
There is a memorised next action '5'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_inform_today' with prob 1.00.
Encountered an exception while running action 'action_inform_today'. Bot will continue, but the actions events are lost. Make sure to fix the exception in your custom code.
The model predicted the custom action 'action_inform_today' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Traceback (most recent call last):
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/processor.py", line 319, in _run_action
    events = action.run(dispatcher, tracker, self.domain)
  File "/usr/local/lib/python3.5/dist-packages/rasa_core/actions/action.py", line 306, in run
    "".format(self.name(), DOCS_BASE_URL))
Exception: The model predicted the custom action 'action_inform_today' but you didn't configure an endpoint to run this custom action. Please take a look at the docs and set an endpoint configuration. https://rasa.com/docs/core/customactions/
Action 'action_inform_today' ended with events '[]'
Current tracker state [{'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'prev_action_listen': 1.0, 'intent_ask_today': 1.0}, {'intent_ask_today': 1.0, 'prev_action_inform_today': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa Core server is up and running on http://localhost:5005
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             HEAD, GET, OPTIONS             /static/[filename]
custom_webhook.health                              HEAD, GET, OPTIONS             /webhooks/rest/
custom_webhook.receive                             OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message '/greet' with intent '{'name': 'greet', 'confidence': 1.0}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 

Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "buttons": null,
  "attachment": null,
  "elements": null
})'
Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/ask' with intent '{'name': 'ask', 'confidence': 1.0}' and entities '[]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 

Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.93.
Action 'action_listen' ended with events '[]'
Rasa process starting
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             GET, OPTIONS, HEAD             /static/[filename]
custom_webhook.health                              GET, OPTIONS, HEAD             /webhooks/rest/
custom_webhook.receive                             OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message '/greet' with intent '{'confidence': 1.0, 'name': 'greet'}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 

Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "elements": null,
  "attachment": null,
  "buttons": null
})'
Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/ask{"time":"week"}' with intent '{'confidence': 1.0, 'name': 'ask'}' and entities '[{'value': 'week', 'end': 19, 'start': 4, 'entity': 'time'}]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 

Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_ask': 1.0, 'entity_time': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.82.
Action 'action_listen' ended with events '[]'
Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             HEAD, OPTIONS, GET             /static/[filename]
custom_webhook.health                              HEAD, OPTIONS, GET             /webhooks/rest/
custom_webhook.receive                             POST, OPTIONS                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9614359736442566}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 

Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_1_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'was gibt's heute zu essen' with intent '{'name': 'ask', 'confidence': 0.9573482871055603}' and entities '[{'entity': 'time', 'end': 16, 'start': 11, 'value': 'heute', 'confidence': 0.9373528474490622, 'extractor': 'ner_crf'}]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 

Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'intent_ask': 1.0, 'prev_action_listen': 1.0, 'entity_time': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.82.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/greet' with intent '{'name': 'greet', 'confidence': 1.0}' and entities '[]'
Logged UserUtterance - tracker now has 8 events
Current slot values: 

Current tracker state [{'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'intent_ask': 1.0, 'prev_action_listen': 1.0, 'entity_time': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.76.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message '/greet' with intent '{'name': 'greet', 'confidence': 1.0}' and entities '[]'
Logged UserUtterance - tracker now has 10 events
Current slot values: 

Current tracker state [{'intent_ask': 1.0, 'prev_action_listen': 1.0, 'entity_time': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 0.72.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.89.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'was gibt es dieses mal' with intent '{'name': 'ask', 'confidence': 0.9593585729598999}' and entities '[]'
Logged UserUtterance - tracker now has 14 events
Current slot values: 

Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'intent_ask': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.81.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9614359736442566}' and entities '[]'
Logged UserUtterance - tracker now has 16 events
Current slot values: 

Current tracker state [{'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'intent_ask': 1.0, 'prev_action_listen': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.75.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9614359736442566}' and entities '[]'
Logged UserUtterance - tracker now has 18 events
Current slot values: 

Current tracker state [{'intent_ask': 1.0, 'prev_action_listen': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 0.71.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.89.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'was gibt diesmal zu essen' with intent '{'name': 'ask', 'confidence': 0.9462840557098389}' and entities '[]'
Logged UserUtterance - tracker now has 22 events
Current slot values: 

Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'intent_ask': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.81.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9614359736442566}' and entities '[]'
Logged UserUtterance - tracker now has 24 events
Current slot values: 

Current tracker state [{'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'intent_ask': 1.0, 'prev_action_listen': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.75.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9614359736442566}' and entities '[]'
Logged UserUtterance - tracker now has 26 events
Current slot values: 

Current tracker state [{'intent_ask': 1.0, 'prev_action_listen': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 0.71.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, wie kann ich helfen?, data: {
  "elements": null,
  "buttons": null,
  "attachment": null
})'
Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.89.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'was gibt es diesmal zu essen' with intent '{'name': 'ask', 'confidence': 0.964856743812561}' and entities '[]'
Logged UserUtterance - tracker now has 30 events
Current slot values: 

Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'intent_ask': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_2_KerasPolicy
Predicted next action 'action_listen' with prob 0.81.
Action 'action_listen' ended with events '[]'
Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             HEAD, OPTIONS, GET             /static/[filename]
custom_webhook.health                              HEAD, OPTIONS, GET             /webhooks/rest/
custom_webhook.receive                             POST, OPTIONS                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9614359736442566}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	scope: None
Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, MensaKL-Bot hier, wie kann ich helfen?, data: {
  "attachment": null,
  "elements": null,
  "buttons": null
})'
Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'was gibt es heute zu essen?' with intent '{'name': 'ask', 'confidence': 0.9706789255142212}' and entities '[{'confidence': 0.9779583080539088, 'entity': 'time', 'extractor': 'ner_crf', 'start': 12, 'value': 'heute', 'end': 17}]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 
	scope: None
Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'intent_ask': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_1_KerasPolicy
Predicted next action 'action_display_meals' with prob 1.00.
Calling action endpoint to run action 'action_display_meals'.
Action 'action_display_meals' ended with events '[]'
Bot utterance 'BotUttered(text: Suche aktuelles Essen für None, data: {
  "attachment": null,
  "elements": null,
  "buttons": null
})'
Bot utterance 'BotUttered(text: Heute gibt es: Pommes, data: {
  "attachment": null,
  "elements": null,
  "buttons": null
})'
Current tracker state [{'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'intent_ask': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}, {'intent_ask': 1.0, 'prev_action_display_meals': 1.0, 'entity_time': 1.0}]
There is no memorised next action
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_1_KerasPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             HEAD, GET, OPTIONS             /static/[filename]
custom_webhook.health                              HEAD, GET, OPTIONS             /webhooks/rest/
custom_webhook.receive                             POST, OPTIONS                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hi there' with intent '{'confidence': 0.9614359736442566, 'name': 'greet'}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	scope: None
Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, MensaKL-Bot hier, wie kann ich helfen?, data: {
  "elements": null,
  "attachment": null,
  "buttons": null
})'
Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'was gibt es heute zu essen' with intent '{'confidence': 0.9706789255142212, 'name': 'ask'}' and entities '[{'entity': 'time', 'confidence': 0.9779583080539088, 'value': 'heute', 'start': 12, 'end': 17, 'extractor': 'ner_crf'}]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 
	scope: None
Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'entity_time': 1.0, 'prev_action_listen': 1.0, 'intent_ask': 1.0}]
There is no memorised next action
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_1_KerasPolicy
Predicted next action 'action_display_meals' with prob 1.00.
Calling action endpoint to run action 'action_display_meals'.
Action 'action_display_meals' ended with events '[]'
Bot utterance 'BotUttered(text: Suche aktuelles Essen für None, data: {
  "elements": null,
  "attachment": null,
  "buttons": null
})'
Bot utterance 'BotUttered(text: Heute gibt es: Pommes, data: {
  "elements": null,
  "attachment": null,
  "buttons": null
})'
Current tracker state [{'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'entity_time': 1.0, 'prev_action_listen': 1.0, 'intent_ask': 1.0}, {'prev_action_display_meals': 1.0, 'intent_ask': 1.0, 'entity_time': 1.0}]
There is no memorised next action
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_1_KerasPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'hi' with intent '{'confidence': 0.9614359736442566, 'name': 'greet'}' and entities '[]'
Logged UserUtterance - tracker now has 11 events
Current slot values: 
	scope: None
Current tracker state [{'entity_time': 1.0, 'prev_action_listen': 1.0, 'intent_ask': 1.0}, {'prev_action_display_meals': 1.0, 'intent_ask': 1.0, 'entity_time': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is no memorised next action
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_1_KerasPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, MensaKL-Bot hier, wie kann ich helfen?, data: {
  "elements": null,
  "attachment": null,
  "buttons": null
})'
Current tracker state [{'prev_action_display_meals': 1.0, 'intent_ask': 1.0, 'entity_time': 1.0}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}]
There is no memorised next action
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_1_KerasPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             OPTIONS, HEAD, GET             /static/[filename]
custom_webhook.health                              OPTIONS, HEAD, GET             /webhooks/rest/
custom_webhook.receive                             OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'jo' with intent '{'confidence': 0.9560196399688721, 'name': 'greet'}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	scope: None
Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, MensaKL-Bot hier, wie kann ich helfen?, data: {
  "attachment": null,
  "elements": null,
  "buttons": null
})'
Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'was gibt es heute zu essen' with intent '{'confidence': 0.9706789255142212, 'name': 'ask'}' and entities '[{'end': 17, 'extractor': 'ner_crf', 'confidence': 0.9779583080539088, 'entity': 'time', 'value': 'heute', 'start': 12}]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 
	scope: None
Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'prev_action_listen': 1.0, 'intent_ask': 1.0, 'entity_time': 1.0}]
There is no memorised next action
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_1_KerasPolicy
Predicted next action 'action_listen' with prob 0.72.
Action 'action_listen' ended with events '[]'
Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             OPTIONS, HEAD, GET             /static/[filename]
custom_webhook.health                              OPTIONS, HEAD, GET             /webhooks/rest/
custom_webhook.receive                             OPTIONS, POST                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'jo' with intent '{'confidence': 0.9560196399688721, 'name': 'greet'}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	scope: None
Current tracker state [None, {}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, MensaKL-Bot hier, wie kann ich helfen?, data: {
  "attachment": null,
  "buttons": null,
  "elements": null
})'
Current tracker state [{}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'was gibt es heute' with intent '{'confidence': 0.9689825177192688, 'name': 'ask'}' and entities '[{'end': 17, 'start': 12, 'extractor': 'ner_crf', 'confidence': 0.9721808209008359, 'entity': 'time', 'value': 'heute'}]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 
	scope: None
Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'entity_time': 1.0, 'intent_ask': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_1_KerasPolicy
Predicted next action 'action_display_meals' with prob 0.70.
Calling action endpoint to run action 'action_display_meals'.
Action 'action_display_meals' ended with events '[]'
Bot utterance 'BotUttered(text: Suche aktuelles Essen für None, data: {
  "attachment": null,
  "buttons": null,
  "elements": null
})'
Bot utterance 'BotUttered(text: Heute gibt es: Pommes, data: {
  "attachment": null,
  "buttons": null,
  "elements": null
})'
Current tracker state [{'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'entity_time': 1.0, 'intent_ask': 1.0, 'prev_action_listen': 1.0}, {'prev_action_display_meals': 1.0, 'entity_time': 1.0, 'intent_ask': 1.0}]
There is no memorised next action
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_1_KerasPolicy
Predicted next action 'action_listen' with prob 0.72.
Action 'action_listen' ended with events '[]'
Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             HEAD, GET, OPTIONS             /static/[filename]
custom_webhook.health                              HEAD, GET, OPTIONS             /webhooks/rest/
custom_webhook.receive                             POST, OPTIONS                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'jo' with intent '{'name': 'greet', 'confidence': 0.9560196399688721}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	scope: None
Current tracker state [None, {}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, MensaKL-Bot hier, wie kann ich helfen?, data: {
  "buttons": null,
  "elements": null,
  "attachment": null
})'
Current tracker state [{}, {'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'was gibt es heute' with intent '{'name': 'ask', 'confidence': 0.9689825177192688}' and entities '[{'end': 17, 'confidence': 0.9721808209008359, 'entity': 'time', 'start': 12, 'value': 'heute', 'extractor': 'ner_crf'}]'
Logged UserUtterance - tracker now has 6 events
Current slot values: 
	scope: None
Current tracker state [{'prev_action_listen': 1.0, 'intent_greet': 1.0}, {'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'prev_action_listen': 1.0, 'intent_ask': 1.0, 'entity_time': 1.0}]
There is no memorised next action
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_1_KerasPolicy
Predicted next action 'action_display_meals' with prob 0.77.
Calling action endpoint to run action 'action_display_meals'.
Action 'action_display_meals' ended with events '[]'
Bot utterance 'BotUttered(text: Suche aktuelles Essen für None, data: {
  "buttons": null,
  "elements": null,
  "attachment": null
})'
Bot utterance 'BotUttered(text: Heute gibt es: Pommes, data: {
  "buttons": null,
  "elements": null,
  "attachment": null
})'
Current tracker state [{'intent_greet': 1.0, 'prev_utter_ask_howcanhelp': 1.0}, {'prev_action_listen': 1.0, 'intent_ask': 1.0, 'entity_time': 1.0}, {'prev_action_display_meals': 1.0, 'intent_ask': 1.0, 'entity_time': 1.0}]
There is no memorised next action
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Feature 'entity_time' (value: '1.0') could not be found in feature map. Make sure you added all intents and entities to the domain
Predicted next action using policy_1_KerasPolicy
Predicted next action 'action_listen' with prob 0.79.
Action 'action_listen' ended with events '[]'
Rasa process starting
Restoring parameters from models/current/nlu/intent_classifier_tensorflow_embedding.ckpt
/usr/local/lib/python3.5/dist-packages/pykwalify/core.py:99: UnsafeLoaderWarning: 
The default 'Loader' for 'load(stream)' without further arguments can be unsafe.
Use 'load(stream, Loader=ruamel.yaml.Loader)' explicitly if that is OK.
Alternatively include the following in your code:

  import warnings
  warnings.simplefilter('ignore', ruamel.yaml.error.UnsafeLoaderWarning)

In most other cases you should consider using 'safe_load(stream)'
  data = yaml.load(stream)

Available web server routes: 
static                                             HEAD, GET, OPTIONS             /static/[filename]
custom_webhook.health                              HEAD, GET, OPTIONS             /webhooks/rest/
custom_webhook.receive                             POST, OPTIONS                  /webhooks/rest/webhook
Rasa Core server is up and running on http://localhost:5005
Creating a new tracker for id 'default'.
Received user message 'hiho' with intent '{'name': None, 'confidence': 0.0}' and entities '[]'
Logged UserUtterance - tracker now has 2 events
Current slot values: 
	time: None
Current tracker state [None, {}, {'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_1_KerasPolicy
Predicted next action 'action_display_meals' with prob 0.57.
Calling action endpoint to run action 'action_display_meals'.
Action 'action_display_meals' ended with events '[]'
Bot utterance 'BotUttered(text: Suche aktuelles Essen für None, data: {
  "attachment": null,
  "elements": null,
  "buttons": null
})'
Bot utterance 'BotUttered(text: Heute gibt es: Pommes, data: {
  "attachment": null,
  "elements": null,
  "buttons": null
})'
Current tracker state [{}, {'prev_action_listen': 1.0}, {'prev_action_display_meals': 1.0}]
There is no memorised next action
Predicted next action using policy_1_KerasPolicy
Predicted next action 'action_listen' with prob 0.60.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9614359736442566}' and entities '[]'
Logged UserUtterance - tracker now has 7 events
Current slot values: 
	time: None
Current tracker state [{'prev_action_listen': 1.0}, {'prev_action_display_meals': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}]
There is no memorised next action
Predicted next action using policy_1_KerasPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 0.63.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, MensaKL-Bot hier, wie kann ich helfen?, data: {
  "attachment": null,
  "elements": null,
  "buttons": null
})'
Current tracker state [{'prev_action_display_meals': 1.0}, {'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}]
There is no memorised next action
Predicted next action using policy_1_KerasPolicy
Predicted next action 'action_listen' with prob 0.79.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'was gibt es heute' with intent '{'name': 'ask', 'confidence': 0.9689825177192688}' and entities '[{'end': 17, 'start': 12, 'confidence': 0.9721808209008359, 'extractor': 'ner_crf', 'value': 'heute', 'entity': 'time'}]'
Logged UserUtterance - tracker now has 12 events
Current slot values: 
	time: heute
Current tracker state [{'intent_greet': 1.0, 'prev_action_listen': 1.0}, {'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask': 1.0, 'slot_time_0': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '5'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'action_display_meals' with prob 1.00.
Calling action endpoint to run action 'action_display_meals'.
Action 'action_display_meals' ended with events '[]'
Bot utterance 'BotUttered(text: Suche aktuelles Essen für heute, data: {
  "attachment": null,
  "elements": null,
  "buttons": null
})'
Bot utterance 'BotUttered(text: Heute gibt es: Pommes, data: {
  "attachment": null,
  "elements": null,
  "buttons": null
})'
Current tracker state [{'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask': 1.0, 'slot_time_0': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}, {'intent_ask': 1.0, 'slot_time_0': 1.0, 'prev_action_display_meals': 1.0, 'entity_time': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9614359736442566}' and entities '[]'
Logged UserUtterance - tracker now has 17 events
Current slot values: 
	time: heute
Current tracker state [{'intent_ask': 1.0, 'slot_time_0': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}, {'intent_ask': 1.0, 'slot_time_0': 1.0, 'prev_action_display_meals': 1.0, 'entity_time': 1.0}, {'intent_greet': 1.0, 'slot_time_0': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, MensaKL-Bot hier, wie kann ich helfen?, data: {
  "attachment": null,
  "elements": null,
  "buttons": null
})'
Current tracker state [{'intent_ask': 1.0, 'slot_time_0': 1.0, 'prev_action_display_meals': 1.0, 'entity_time': 1.0}, {'intent_greet': 1.0, 'slot_time_0': 1.0, 'prev_action_listen': 1.0}, {'slot_time_0': 1.0, 'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'was gibt es diese woche' with intent '{'name': 'ask', 'confidence': 0.9556897878646851}' and entities '[{'end': 23, 'start': 18, 'confidence': 0.8816537979469949, 'extractor': 'ner_crf', 'value': 'woche', 'entity': 'time'}]'
Logged UserUtterance - tracker now has 22 events
Current slot values: 
	time: woche
Current tracker state [{'intent_greet': 1.0, 'slot_time_0': 1.0, 'prev_action_listen': 1.0}, {'slot_time_0': 1.0, 'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask': 1.0, 'slot_time_0': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '5'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'action_display_meals' with prob 1.00.
Calling action endpoint to run action 'action_display_meals'.
Action 'action_display_meals' ended with events '[]'
Bot utterance 'BotUttered(text: Suche aktuelles Essen für woche, data: {
  "attachment": null,
  "elements": null,
  "buttons": null
})'
Bot utterance 'BotUttered(text: Heute gibt es: Pommes, data: {
  "attachment": null,
  "elements": null,
  "buttons": null
})'
Current tracker state [{'slot_time_0': 1.0, 'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask': 1.0, 'slot_time_0': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}, {'intent_ask': 1.0, 'slot_time_0': 1.0, 'prev_action_display_meals': 1.0, 'entity_time': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'hi' with intent '{'name': 'greet', 'confidence': 0.9614359736442566}' and entities '[]'
Logged UserUtterance - tracker now has 27 events
Current slot values: 
	time: woche
Current tracker state [{'intent_ask': 1.0, 'slot_time_0': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}, {'intent_ask': 1.0, 'slot_time_0': 1.0, 'prev_action_display_meals': 1.0, 'entity_time': 1.0}, {'intent_greet': 1.0, 'slot_time_0': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '3'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'utter_ask_howcanhelp' with prob 1.00.
Action 'utter_ask_howcanhelp' ended with events '[]'
Bot utterance 'BotUttered(text: Hi, MensaKL-Bot hier, wie kann ich helfen?, data: {
  "attachment": null,
  "elements": null,
  "buttons": null
})'
Current tracker state [{'intent_ask': 1.0, 'slot_time_0': 1.0, 'prev_action_display_meals': 1.0, 'entity_time': 1.0}, {'intent_greet': 1.0, 'slot_time_0': 1.0, 'prev_action_listen': 1.0}, {'slot_time_0': 1.0, 'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
Recreating tracker for id 'default'
Received user message 'was gibt's die woche?' with intent '{'name': 'ask', 'confidence': 0.9039351940155029}' and entities '[{'end': 20, 'start': 15, 'confidence': 0.7812152507826553, 'extractor': 'ner_crf', 'value': 'woche', 'entity': 'time'}]'
Logged UserUtterance - tracker now has 32 events
Current slot values: 
	time: woche
Current tracker state [{'intent_greet': 1.0, 'slot_time_0': 1.0, 'prev_action_listen': 1.0}, {'slot_time_0': 1.0, 'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask': 1.0, 'slot_time_0': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}]
There is a memorised next action '5'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'action_display_meals' with prob 1.00.
Calling action endpoint to run action 'action_display_meals'.
Action 'action_display_meals' ended with events '[]'
Bot utterance 'BotUttered(text: Suche aktuelles Essen für woche, data: {
  "attachment": null,
  "elements": null,
  "buttons": null
})'
Bot utterance 'BotUttered(text: Heute gibt es: Pommes, data: {
  "attachment": null,
  "elements": null,
  "buttons": null
})'
Current tracker state [{'slot_time_0': 1.0, 'prev_utter_ask_howcanhelp': 1.0, 'intent_greet': 1.0}, {'intent_ask': 1.0, 'slot_time_0': 1.0, 'entity_time': 1.0, 'prev_action_listen': 1.0}, {'intent_ask': 1.0, 'slot_time_0': 1.0, 'prev_action_display_meals': 1.0, 'entity_time': 1.0}]
There is a memorised next action '0'
Predicted next action using policy_0_MemoizationPolicy
Predicted next action 'action_listen' with prob 1.00.
Action 'action_listen' ended with events '[]'
